# Generated by Django 4.1 on 2022-09-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
