# Generated by Django 4.1 on 2022-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images4',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
