# Generated by Django 4.1 on 2022-08-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_images2_product_images3_product_images4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images4',
            new_name='image4',
        ),
    ]
