# Generated by Django 4.1 on 2022-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
