# Generated by Django 4.1 on 2022-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_image2_remove_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='store/products/{{product.product_name}}'),
        ),
    ]
